name: Installing And Testing
on:
  push:
    branches: [main, devops/git-actions]
    
jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    env:
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Install 
        run: yarn install
      - name: Test
        run: yarn test