name: Quality Check

on:
  push:
    branches:
      - main
      - devops/git-actions

jobs:
  install-packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install

  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21x]

    needs: install-packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Run tests
        run: yarn test
